services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    container_name: frontend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - "POSTGRES_PASSWORD=55aa"
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/db
    ports:
      - '5433:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    
