services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend

  backend:
    build: ./backend
    ports:
      - "10000:10000"
    container_name: backend

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data