#postgres
DbAddr: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
#server
Port: 8080
#redis
RedisAddr: localhost:6379
RedisPassword: 55aa
#JWT
JWTSecret: WgyCXpzAOJkkQUWjztqiwBWOYstBDJSfKmzQiQkEqpPePKTmyhosQlAqVZAaaoDsSSlVBUNB
#https
UseSSL: false
