#postgres
DbAddr: postgres://postgres:55aa@postgres:5432/dchat?sslmode=disable
#server
Port: 8080
#redis
UseRedis: false
RedisAddr: localhost:6379
RedisPassword: 55aa
#JWT
JWTSecret: WgyCXpzAOJkkQUWjztqiwBWOYstBDJSfKmzQiQkEqpPePKTmyhosQlAqVZAaaoDsSSlVBUNB
#https
UseSSL: false
