#postgres
DbAddr: postgres://postgres:55aa@localhost:5432/dchat
#server
Port: 8080
#redis
UseRedis: false
RedisAddr: localhost:6379
RedisPassword: 1234
#JWT
JWTSecret: WgyCXpzAOJkkQUWjztqiwBWOYstBDJSfKmzQiQkEqpPePKTmyhosQlAqVZAaaoDsSSlVBUNB
#https
UseSSL: false
