#postgres
DbAddr: postgres://postgres:1234@postgres:5432/dchat?sslmode=disable
#server
Port: 8080
#redis
UseRedis: false
RedisAddr: localhost:6379
RedisPassword: 1234
#JWT
JWTSecret: WgyCXpzAOJkkQUWjztqiwBWOYstBDJSfKmzQiQkEqpPePKTmyhosQlAqVZAaaoDsSSlVBUNB
#https
UseSSL: false
#fileLog
UseFileLog: true