#postgres
DbAddr: postgres://postgres:55aa@127.0.0.1:5433/dchat?sslmode=disable
#server
Port: 10000
#redis
RedisAddr: localhost:6379
RedisPassword: 55aa
#JWT
JWTSecret: B4qicI8CP8oDGTjwUdwbCpfFZO7k2PQQKdHVdEvYjQJeYIDB
#https
UseSSL: false
